apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfohelsenettproxy
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  redis:
    - instance: syfohelsenettproxy
      access: readwrite
  accessPolicy:
    inbound:
      rules:
        - application: syfosmmottak
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: syfosmregler
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: syfosminfotrygd
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: syfosmpapirregler
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: syfosmpapirmottak
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: smregistrering-backend
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: pale-2-regler
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: padm2
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: hm-brille-api
          namespace: teamdigihot
          cluster: dev-gcp
        - application: pale-2-sak
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: teamsykmelding-mock-backend
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: btsys
          namespace: team-rocket
          cluster: dev-fss
        - application: journalforing-frontend-q2
          namespace: isa
          cluster: dev-gcp
        - application: journalforing-frontend-q1
          namespace: isa
          cluster: dev-gcp
    outbound:
      external:
        - host: ws.test.nhn.no
  ingresses:
    - "https://syfohelsenettproxy.intern.dev.nav.no"
  secureLogs:
    enabled: true
  tokenx:
    enabled: true
  envFrom:
    - secret: syfohelsenettproxy-secrets
  env:
    - name: HELSEPERSONELL_V1_ENDPOINT_URL
      value: https://ws.test.nhn.no/v2/HPR/Basic
