apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfohelsenettproxy
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 80
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  resources:
    limits:
      memory: 9048Mi
    requests:
      cpu: 100m
      memory: 7048Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
  redis:
    - instance: syfohelsenettproxy
      access: readwrite
  accessPolicy:
    inbound:
      rules:
        - application: syfosmmottak
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: statistikkforsykmelder-legacy
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syfosmregler
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syfosminfotrygd
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syfosmpapirmottak
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syfosmpapirregler
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: smregistrering-backend
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: pale-2-regler
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: padm2
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: isdialogmelding
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: hm-brille-api
          namespace: teamdigihot
          cluster: prod-gcp
        - application: pale-2-sak
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: btsys-api
          namespace: team-rocket
          cluster: prod-gcp
        - application: journalforing-frontend
          namespace: isa
          cluster: prod-gcp
    outbound:
      external:
        - host: ws.nhn.no
  secureLogs:
    enabled: true
  tokenx:
    enabled: true
  envFrom:
    - secret: syfohelsenettproxy-secrets
  env:
    - name: HELSEPERSONELL_V1_ENDPOINT_URL
      value: https://ws.nhn.no/v2/HPR/Basic
    - name: FASTLEGEINFORMASJON_V2_ENDPOINT_URL
      value: https://ws.nhn.no/v2/flrexport